sudo: required
services:
  - docker

before_install:
  - docker build -t tarunsuneja/react-test -f ./client/DockerFile.dev ./client

script:
  - docker run -e CI=true tarunsuneja/react-test npm test

after_success:
  - docker build -t tarunsuneja/learn-multi-client ./client
  - docker build -t tarunsuneja/learn-multi-server ./server
  - docker build -t tarunsuneja/learn-multi-nginx ./nginx
  - docker build -t tarunsuneja/learn-multi-worker ./worker

  # Login to Docker CLI
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_ID" --password-stdin

  # Take those images and push to docker hub
  - docker push tarunsuneja/learn-multi-client
  - docker push tarunsuneja/learn-multi-server
  - docker push tarunsuneja/learn-multi-nginx
  - docker push tarunsuneja/learn-multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-042921395286
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
#deploy:
#  edge: true
#  provider: elasticbeanstalk
